### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by doug-skinner**
Hello!

I saw this posted on the reddit page a couple days ago and wanted to help you out with your basic design that you had going. I updated it to use some of the bootstrap 3 styling, and would be happy to explain any of the changes that I made.

Screenshot One, the homepage:
screen shot 2018-01-15 at 5 57 23 pm

Screenshot Two, the search page:
screen shot 2018-01-15 at 5 57 36 pm

Screenshot Three, the search page with errors:
screen shot 2018-01-15 at 5 57 48 pm

### CODE REVIEW

**Comment by brettvanderwerff** [comment]
Wow, I’m really excited that someone looked at this! Thank you for taking the time to put in the pull request. When I was making this, I didn’t really know how to do front end and was more worried about the functionality of the map maker itself. My “approach” to front end was basically to install flask-bootstrap and then copy and paste things I liked from this resource: 

https://www.w3schools.com/bootstrap/bootstrap_get_started.asp 

Some things that you did I understand, like passing variables through the render_template function, but honestly most of what you did here with bootstrap 3 is a black box to me. I know I have to actually learn proper front end if I want to make good looking flask apps, so how did you go about learning this material? Is there a resource you would recommend starting with? I will merge these changes as soon as I can, I really liked what you did here, so thanks again!

**Comment by doug-skinner** [comment]
While I don't have a specific resource that I used for this, two things that have helped me a lot with front end is reading the [webdesign](https://www.reddit.com/r/web_design/) subreddit and also looking at Google's material design guidelines. 

I would also look into using the actual [bootstrap,](https://getbootstrap.com) rather than the package version of bootstrap 3 that you were using. The newest version of bootstrap includes a lot of good examples, and can be loaded remotely like your api calls so you don't have to include the files in your repo. 

I'm glad you like the design, and feel free to reach out to the email on my profile with any more questions.

**Comment by brettvanderwerff** [comment]
Great. Thanks for the tips. I think I'll start by studying what you did and looking at the actual bootstrap. I really enjoy working with flask and have another app in the workings, so the sooner I get some kind of handle on the front end the better!

**Comment by doug-skinner** [comment]
Hey, not quite sure if you're going to see this on the closed merge request or not, but after answering the other day I thought I would try to give a slightly more thorough answer. A short write up going change by change can be found [here](https://doug-skinner.com/writing/2018/01/19/Mushroom-Redesign.html). Let me know if you find it helpful at all, and my email address is on that page if you need any help in the future. Good luck with your future projects.

**Comment by brettvanderwerff** [comment]
Oh wow a whole blog post about the mushroom map maker. I feel honored! I am trying to familiarize myself with bootstrap 4 by using a tutorial right now and the blog post is going to help me understand what you did better. I think I'm done with the map maker for now. I'm working on the main functionality of another flask app that uses ebay's API to analyze digital media prices daily. I'm going to try and go straight to using bootstrap 4 and no use the flask-bootstrap package. Hopefully it looks better than what mushroom map maker started out as!

**Pull request merged**
